### ISSUE TITLE
ERROR git diff with force-dev-tool changeset create 

### ISSUE THREAD

**Issue by rodolfonoviski** [amtrack/force-dev-tool#101]
When I try to generate a changeset with the difference between two branchs it returns the following error:

`
TypeError: Cannot read property 'type' of null
    at module.exports.Manifest.add (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\manifest.js:56:19)
    at C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:174:42
    at Array.forEach (<anonymous>)
    at module.exports.MetadataContainer.diff (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:161:15)
    at Socket.<anonymous> (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\cli\changeset.js:74:38)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
`

**Comment by amtrack** [comment]
@rodolfonoviski Can you please provide the following information:

- Output of `force-dev-tool --version`
- Have you commited your changes before running the command (e.g. `git add -A; git commit -m "my changes"`)?

**Comment by rodolfonoviski** [comment]
$ force-dev-tool --version
1.0.0

Yes I did commit and push to git server

**Comment by amtrack** [comment]
Could you send me the list of changed files (`git diff --name-status`) in a secret Gist (https://gist.github.com) and email me the link to mr.amtrack@gmail.com?

**Comment by rodolfonoviski** [comment]
I just sent you

**Comment by rodolfonoviski** [comment]
@amtrack Now it is returning this error:
`TypeError: field.childNamed is not a function
    at C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:110:29
    at Array.forEach (<anonymous>)
    at C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:109:44
    at Array.forEach (<anonymous>)
    at module.exports.MetadataFileContainer.parse (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:106:22)
    at module.exports.MetadataFileContainer.diff (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:45:8)
    at C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:169:26
    at Array.forEach (<anonymous>)
    at module.exports.MetadataContainer.diff (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:161:15)
    at Socket.<anonymous> (C:\Users\rnoviski\AppData\Roaming\npm\node_modules\force-dev-tool\lib\cli\changeset.js:74:38)
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>40.0</version>
</Package>

exported metadata container to config\deployments\deploy0712

`

**Comment by amtrack** [comment]
The latest error should be fixed on the master branch.

Can you try using the latest version

```console
$ npm install -g git+http://github.com/amtrack/force-dev-tool.git#master
```

**Comment by rodolfonoviski** [comment]
Thank you very much for your attention. It worked now !

**Comment by amtrack** [comment]
OK, great!
I guess I need to publish a new release soon.

**Comment by rodolfonoviski** [comment]
@amtrack I am waiting for updates because its solution is incredible. Help me a lot in the DevOps process.
