### ISSUE TITLE
Error: TypeError: field.childNamed is not a function

### ISSUE THREAD

**Issue by nithyusha23** [amtrack/force-dev-tool#107]
Modified a file in WorkFlow and when tried to generate package.xml file, got following error:

<?xml version="1.0" encoding="UTF-8"?>

<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>Case_Email_Notification_to_After_Hours_Corp_Public_Group</fullName>
        <description>[Case] Email Notification to After Hours Corp Public Group</description>
        <protected>false</protected>
        <recipients>
            <recipient>After_Hours_Notifications_Corp</recipient>
            <type>group</type>
        </recipients>
        <senderType>DefaultWorkflowUser</senderType>
        <template>Cases/Case_After_Hours_Notification</template>
    </alerts>

Error:
TypeError: field.childNamed is not a function
    at C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:110:29
    at Array.forEach (<anonymous>)
    at C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:109:44
    at Array.forEach (<anonymous>)
    at module.exports.MetadataFileContainer.parse (C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:106:22)
    at module.exports.MetadataFileContainer.diff (C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:45:8)
    at C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:169:26
    at Array.forEach (<anonymous>)
    at module.exports.MetadataContainer.diff (C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:161:15)
    at Socket.<anonymous> (C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\cli\changeset.js:74:38)
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>38.0</version>
</Package>

**Comment by amtrack** [comment]
Please install the latest `force-dev-tool` (master branch) using

```console
$ npm install git+https://github.com/amtrack/force-dev-tool.git
```

**Comment by nithyusha23** [comment]
Still I am getting same error:
C:\Users\Nithyusha_Gurujala1\Ipreotest>npm install git+https://github.com/amtrack/force-dev-tool.git
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Nithyusha_Gurujala1\Ipreotest\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Nithyusha_Gurujala1\Ipreotest\package.json'
npm WARN Ipreotest No description
npm WARN Ipreotest No repository field.
npm WARN Ipreotest No README data
npm WARN Ipreotest No license field.

+ force-dev-tool@1.0.0
added 210 packages in 44.62s

C:\Users\Nithyusha_Gurujala1\Ipreotest>rmdir /s /q config

C:\Users\Nithyusha_Gurujala1\Ipreotest>git diff 61b34583 27e86905 | force-dev-tool changeset create vat
TypeError: field.childNamed is not a function
    at C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:110:29
    at Array.forEach (<anonymous>)
    at C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:109:44
    at Array.forEach (<anonymous>)
    at module.exports.MetadataFileContainer.parse (C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:106:22)
    at module.exports.MetadataFileContainer.diff (C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-file-container.js:45:8)
    at C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:169:26
    at Array.forEach (<anonymous>)
    at module.exports.MetadataContainer.diff (C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:161:15)
    at Socket.<anonymous> (C:\Users\Nithyusha_Gurujala1\AppData\Roaming\npm\node_modules\force-dev-tool\lib\cli\changeset.js:74:38)
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>38.0</version>
</Package>

**Comment by nithyusha23** [comment]
It worked... Thank you.

**Comment by amtrack** [comment]
In this case you are probably using a globally installed force-dev-tool.

So you would need to install the latest force-dev-tool globally as well (`-g`):

```console
$ npm install -g git+https://github.com/amtrack/force-dev-tool.git
```
