### ISSUE TITLE
how to deploy page layout by explicitly listing components, getting below error

### ISSUE THREAD

**Issue by Nazareena** [amtrack/force-dev-tool#184]
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1143:5)
    at module.exports.DescribeMetadataService.getTypeForFilepath (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/describe-metadata-service.js:374:41)
    at /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/metadata-container.js:210:43
    at Array.forEach (<anonymous>)
    at module.exports.MetadataContainer.determineMissingFiles (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/metadata-container.js:209:31)
    at module.exports.MetadataContainer.completeMetadataWith (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/metadata-container.js:253:26)
    at DestroyableTransform._transform (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/metadata-container.js:360:41)
    at DestroyableTransform.Transform._read (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/node_modules/readable-stream/lib/_stream_transform.js:172:83)

**Comment by amtrack** [comment]
@Nazareena Please, if you need help, you should at least provide the steps to reproduce this error or give a more precise example to underline your question.

To deploy a certain page layout, i would do s.th. like this:

```console
force-dev-tool changeset create mypagelayout "Layout/Account-Account Layout"
force-dev-tool deploy -d config/deployments/mypagelayout
```

**Comment by Nazareena** [comment]
Yes its working I think issue is when i pass that as parameter , i will check on that.
