### ISSUE TITLE
/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/manifest.js:57 			type: component.type, 			                ^  TypeError: Cannot read property 'type' of null     at module.exports.Manifest.add (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/manifest.js:57:20)     at /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/metadata-container.js:337:43     at Array.forEach (<anonymous>)

### ISSUE THREAD

**Issue by ChinthapatlaRavali** [amtrack/force-dev-tool#202]
we are getting this issue please lte us know how we can debug the issue.
/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/manifest.js:57
			type: component.type,
			                ^

TypeError: Cannot read property 'type' of null
    at module.exports.Manifest.add (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/manifest.js:57:20)
    at /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/RecentNode/lib/node_modules/force-dev-tool/lib/metadata-container.js:337:43
    at Array.forEach (<anonymous>)

**Comment by Nazareena** [comment]
Please let me know how i can debug the issue in force-dev-tool

**Comment by amtrack** [comment]
@ChinthapatlaRavali @Nazareena To debug an issue, it would be very helpful to get some context about this error:

- What command were you running?
- What version of `Node.js` and `force-dev-tool` are you running?

**Comment by Nazareena** [comment]
When there is some difference identified in gb_tables for the package creation we are facing this issue.

**Comment by amtrack** [comment]
@Nazareena i don't know what you mean with `gb_tables`. Maybe you are referring to a term used in your company or org.

**Comment by ChinthapatlaRavali** [comment]
Its something related to gridbuddy json files, for now we ignored that difference and able to build the package. Thanks.

**Comment by Nazareena** [comment]
Its something related to grid buddy json files in our org , for now we have ignored those files and created the package.Thanks

**Comment by amtrack** [comment]
@Nazareena In this case, please also attach the content (anonymized if necessary) of your `.forceignore` with the information mentioned above (https://github.com/amtrack/force-dev-tool/issues/202#issuecomment-512177736).

**Comment by amtrack** [comment]
closing because of inactivity
