### ISSUE TITLE
echo "" | force-dev-tool changeset create Deploy src/classes/AccountHelper.cls causes error

### ISSUE THREAD

**Issue by g1b3r** [amtrack/force-dev-tool#206]
When i try to do this i got a error additionaly i cannot add more that 2 elements to create changeset

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at module.exports.DescribeMetadataService.getTypeForFilepath (/usr/lib/node_modules/force-dev-tool/lib/describe-metadata-service.js:374:41)
    at /usr/lib/node_modules/force-dev-tool/lib/metadata-container.js:210:43
    at Array.forEach (<anonymous>)
    at module.exports.MetadataContainer.determineMissingFiles (/usr/lib/node_modules/force-dev-tool/lib/metadata-container.js:209:31)
    at module.exports.MetadataContainer.completeMetadataWith (/usr/lib/node_modules/force-dev-tool/lib/metadata-container.js:253:26)
    at DestroyableTransform._transform (/usr/lib/node_modules/force-dev-tool/lib/metadata-container.js:360:41)
    at DestroyableTransform.Transform._read (/usr/lib/node_modules/force-dev-tool/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/lib/node_modules/force-dev-tool/node_modules/readable-stream/lib/_stream_transform.js:172:83)

latest npm version 
force dev tool version 2.4.0 
latest reac version 

I think there can be problem with string lenght 

BR

**Comment by amtrack** [comment]
@g1b3r I'm getting the same error when the file does not exist.
Are you sure that `src/classes/AccountHelper.cls` exists?

**Comment by g1b3r** [comment]
Yes im sure its here :)

**Comment by g1b3r** [comment]
If i try to add for example 3 classes i got similiar error. On 2 working fine. I think there is a problem with lenght of string :(

**Comment by amtrack** [comment]
@g1b3r Could you please try if the new release ([2.8.3](https://github.com/amtrack/force-dev-tool/releases/tag/v2.8.3)) resolves this issue?

**Comment by g1b3r** [comment]
Sorry for late comment :) its looks like it works :) @amtrack thank you :)
