### ISSUE TITLE
Facing the Socket disconnect error while retrieving  the metadata from the orgs

### ISSUE THREAD

**Issue by 92SGupta** [amtrack/force-dev-tool#210]
When i am trying to run the command to fetch the metadata from the org. I am getting below error:

Retrieving from remote vb02 to directory ../packages/Item-10382_vlocityb02/src
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:299:28)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: undefined,
  port: 0,
  localAddress: undefined
}
Error: Client network socket disconnected before secure TLS connection was established

I have already upgraded my node version to 12.12.0 and Force-dev-tool version to 2.4.2 but still the same issue . Does anyone has any idea as how to resolve this issue? 

Note: This issue is intermittent and is doesn't impacts all the orgs at the same time.

force-dev-tool retrieve -d Item-10382_vlocityb02/src/
Retrieving from remote vb02 to directory ../packages/Item-10382_vlocityb02/src
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:299:28)
    at TLSSocket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: undefined,
  port: 0,
  localAddress: undefined
}
Error: Client network socket disconnected before secure TLS connection was established

**Comment by 92SGupta** [comment]
Thanks @amtrack 

> @92SGupta This looks like a network issue to me.
> I don't think, that we can do something in force-dev-tool to prevent those issues.
> 
> I'm not a network expert, but to investigate such an issue, i would do the following:
> 
> * check https://status.salesforce.com
> * check settings of security software installed on the machine
> * run from another machine
> * run from another network
> * change DNS servers

Thanks @amtrack . I know that this is not related to force-dev-tool as this error is happening for sfdx as well but just wanted to know if anyone has faced this issue earlier. Thanks for the investigation steps.
