### ISSUE TITLE
Error creating changeset from diff using version 2.8.2

### ISSUE THREAD

**Issue by asheehanbhtp** [amtrack/force-dev-tool#261]
When trying to create a changeset from a git diff, the following error occurs. I have been able to reproduce on both MacOs and CentOS. Reverting to the previous version (2.8.1) resolves the error.

```
git diff --no-renames origin/master HEAD | force-dev-tool changeset create -f deploy

~/Source/sfdc/node_modules/parse-diff/index.js:158
  fileNames.map(function(fileName, i) {
            ^

TypeError: Cannot read property 'map' of null
    at parseFile (~/Source/sfdc/node_modules/parse-diff/index.js:158:13)
    at Array.start (~/Source/sfdc/node_modules/parse-diff/index.js:33:19)
    at parse (~/Source/sfdc/node_modules/parse-diff/index.js:139:13)
    at module.exports (~/Source/sfdc/node_modules/parse-diff/index.js:147:5)
    at DestroyableTransform._transform (~/Source/sfdc/node_modules/force-dev-tool/lib/diff.js:65:15)
    at DestroyableTransform.Transform._read (~/Source/sfdc/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (~/Source/sfdc/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (~/Source/sfdc/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (~/Source/sfdc/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (~/Source/sfdc/node_modules/readable-stream/lib/_stream_writable.js:334:11)
```

git version 2.26.0
node version v12.16.1
force-dev-tool version 2.8.2

**Comment by amtrack** [comment]
@asheehanbhtp Thank you for reporting this issue!
It would be great if you could provide as much information as needed to reproduce this as I'm currently busy chasing another bug.

**Comment by amtrack** [comment]
@asheehanbhtp Could you please try if the new release ([2.8.3](https://github.com/amtrack/force-dev-tool/releases/tag/v2.8.3)) resolves this issue?

**Comment by esteele** [comment]
I'm seeing the same issue. Tried 2.8.3, but it's still failing.

**Comment by froucher** [comment]
Please, can you try with the last version 2.8.4?

Thank you

**Comment by asheehanbhtp** [comment]
@froucher, the changes in the most recent release seem to have resolved the issues I was originally facing. For whatever reason, once we incorporated more changes into our repo, this issue went away.

Thank you.
