### ISSUE TITLE
Package.xml and src components generation fails with v1.0

### ISSUE THREAD

**Issue by okram999** [amtrack/force-dev-tool#94]
Will update more log details, but not sure if u are aware of this already 

**updated the console log:**

```
+ node --version
v8.1.4
+ npm install --global force-dev-tool
/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/bin/force-dev-tool -> /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/lib/node_modules/force-dev-tool/bin/cli
+ force-dev-tool@1.0.0
updated 1 package in 2.64s
+ git fetch --all
Fetching origin
+ git branch -a
* (detached from b2195ea)
  remotes/origin/config
  remotes/origin/configChanges_config_demo
  remotes/origin/configChanges_config_test_sample
  remotes/origin/config_test
  remotes/origin/dev
  remotes/origin/master
  remotes/origin/test_config
+ git checkout config_test
Switched to a new branch 'config_test'
Branch config_test set up to track remote branch config_test from origin.
+ git checkout configChanges_config_test_sample
Switched to a new branch 'configChanges_config_test_sample'
Branch configChanges_config_test_sample set up to track remote branch configChanges_config_test_sample from origin.
+ git diff config_test configChanges_config_test_sample
+ force-dev-tool changeset create devDeploy
TypeError: field.childNamed is not a function
    at /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/lib/node_modules/force-dev-tool/lib/metadata-file-container.js:110:29
    at Array.forEach (native)
    at /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/lib/node_modules/force-dev-tool/lib/metadata-file-container.js:109:44
    at Array.forEach (native)
    at module.exports.MetadataFileContainer.parse (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/lib/node_modules/force-dev-tool/lib/metadata-file-container.js:106:22)
    at module.exports.MetadataFileContainer.diff (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/lib/node_modules/force-dev-tool/lib/metadata-file-container.js:45:8)
    at /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/lib/node_modules/force-dev-tool/lib/metadata-container.js:169:26
    at Array.forEach (native)
    at module.exports.MetadataContainer.diff (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/lib/node_modules/force-dev-tool/lib/metadata-container.js:161:15)
    at Socket.<anonymous> (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs814/lib/node_modules/force-dev-tool/lib/cli/changeset.js:74:38)
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>38.0</version>
</Package>
```

Reverted to the previous version: **force-dev-tool@0.13.1**   and it works! 

Not a javascript guys, but starting to look into it. but looks like the issue occured while generating the package.xml (i have removed various members, but i left the metadata components, to kind of give you an idea on what components were involved. 

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>OpportunityHierarchyExtension</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>User.Job_Function__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Account-ABCDEF Asset Services %26 VAS - Account Layout</members>
        <members>Contact-ABCDEF Asset Services %26 VAS - Contact Layout</members>
        <name>Layout</name>
    </types>
    <types>
        <members>Case.APAC_Support_Tickets_Active</members>
        <name>ListView</name>
    </types>
    <types>
        <members>Process_Builder_Permission</members>
        <members>Regional_Business_Support</members>
        <members>Reports_Dashboards_Data_Export_for_Super_Users</members>
        <members>Tableau_Dashboard_Permission</members>
        <members>UK_Key_Contact_Segmentation_Permissions</members>
        <members>VAS_Account_Field_Rights</members>
        <name>PermissionSet</name>
    </types>
    <types>
        <members>SolutionManager</members>
        <members>Standard</members>
        <name>Profile</name>
    </types>
    <types>
        <members>Quote.SendEmail</members>
        <members>SendEmail</members>
        <name>QuickAction</name>
    </types>
    <types>
        <members>Task.EMEA_Task</members>
        <name>RecordType</name>
    </types>
    <types>
        <members>Valuations_Services</members>
        <name>Role</name>
    </types>
    <types>
        <members>Opportunity.NextStepMustBeFilledInBeforeClosed</members>
        <members>Opportunity.Preventt</members>
        <name>ValidationRule</name>
    </types>
    <types>
        <members>Contact.Move_Contract</members>
        <name>WebLink</name>
    </types>
    <types>
        <members>Account.AutopopulateSiteName</members>
        <name>WorkflowRule</name>
    </types>
    <version>38.0</version>
</Package>

```

**Comment by okram999** [comment]
hi @amtrack , any idea on this?

**Comment by amtrack** [comment]
@okram999, 
It seems that this error was related to the WorkflowRule Metadata Type (see #97). It should now be fixed on the master branch.
Please install force-dev-tool using `npm install git+https://github.com/amtrack/force-dev-tool.git` until a new release has been published.
