### ISSUE TITLE
TypeError: field.childNamed is not a function

### ISSUE THREAD

**Issue by BobHatcher** [amtrack/force-dev-tool#97]
Hi,

We are trying to create a changeset by doing a diff on two branches.

`git diff develop feature/marketing | force-dev-tool changeset create mkt_diff `

when I do that, I get an error. Here's the stack trace.

TypeError: field.childNamed is not a function
    at /usr/local/lib/node_modules/force-dev-tool/lib/metadata-file-container.js:110:29
    at Array.forEach (native)
    at /usr/local/lib/node_modules/force-dev-tool/lib/metadata-file-container.js:109:44
    at Array.forEach (native)
    at MetadataFileContainer.parse (/usr/local/lib/node_modules/force-dev-tool/lib/metadata-file-container.js:106:22)
    at MetadataFileContainer.diff (/usr/local/lib/node_modules/force-dev-tool/lib/metadata-file-container.js:45:8)
    at /usr/local/lib/node_modules/force-dev-tool/lib/metadata-container.js:169:26
    at Array.forEach (native)
    at MetadataContainer.diff (/usr/local/lib/node_modules/force-dev-tool/lib/metadata-container.js:161:15)
    at Socket.<anonymous> (/usr/local/lib/node_modules/force-dev-tool/lib/cli/changeset.js:74:38)
Manifest:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>38.0</version>
</Package>

exported metadata container to config/deployments/mkt_diff

Forgive me if this is elementary, we're a little new to this. We installed the tool using `npm install` this morning, so we believe this is the latest version.

Thanks in advance!

**Comment by BobHatcher** [comment]
To add to this, we have identified that this only occurs when we include Opportunity and Contact workflows.

**Comment by amtrack** [comment]
@BobHatcher Thanks for reporting!
I just fixed this on the master branch.
Please install force-dev-tool using `npm install git+https://github.com/amtrack/force-dev-tool.git` until a new release has been published.

**Comment by BobHatcher** [comment]
Thank you!
